# Site settings
title: Justin Breese | random thoughts
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  TBD
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://justinbreese.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: justinbreese
github_username:  justinbreese

css_inline: true

# Build settings ##############################################################
# theme: minima
# theme: alembic-jekyll-theme
remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-commonmark
  - jekyll-include-cache

# Gem settings #################################################################
paginate: 5 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: justinbreese # jekyll-seo-tag > Owners twitter username
author: justinbreese # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Justin Breese # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/justinbreese
    - https://www.linkedin.com/in/justinbreese
    - https://github.com/justinbreese

# Navigation
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/
- title: Search
  url: /search/

navigation_footer:
- title: Created by Justin Breese Ⓒ 2021
  url: https://justinbreese.com

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/justinbreese
  LinkedIn: https://www.linkedin.com/in/justinbreese
  GitHub: https://github.com/justinbreese
  link: https://justinbreese.com
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Excludes #######################################

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - alembic-jekyll-theme.gemspec
  - .jekyll-cache
  - CNAME
